// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgmxeqpcslxxctfuscru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbXhlcXBjc2x4eGN0ZnVzY3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTczNTcsImV4cCI6MjA2NTUzMzM1N30.Nivc0kGuZu-1LtR8epSKS4_mmmEzEp_TSIX_0QoNc5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);